# Generated by Django 3.0 on 2020-03-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='fit',
            field=models.CharField(blank=True, choices=[('P', 'POTENTIAL FIT'), ('W', 'WATCH LIST'), ('N', 'NOT A FIT')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hacker',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackers', to='clients.Startup'),
        ),
    ]
