# Generated by Django 3.0 on 2020-03-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200326_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('applied_at', models.DateTimeField()),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('hacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='clients.Hacker')),
            ],
        ),
    ]
