# Generated by Django 3.0 on 2020-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='external_id',
            field=models.BigIntegerField(),
        ),
    ]
