# Generated by Django 3.0 on 2020-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200327_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('external_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_applications', to='clients.JobPosition'),
        ),
    ]
