# Generated by Django 3.0 on 2020-03-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200327_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hacker',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='hacker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
