# Generated by Django 3.0 on 2020-04-01 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200331_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
