# Generated by Django 3.0 on 2020-04-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20200401_0932'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='clients.Startup'),
        ),
    ]
