# Generated by Django 3.0 on 2020-04-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200415_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_deals', to='sales.DealType'),
        ),
    ]
